# Generated by Django 5.1.4 on 2025-01-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='none', max_length=255, unique=True, verbose_name='slug'),
        ),
    ]
